const cardData = [

    {
        _id: '1',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },

    {
        _id: '2',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '3',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '4',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '5',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '6',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '7',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },
    {
        _id: '8',
        mainName: "Tiger",
        mainDesc: "Something in main Desc",
        mainImage: "",
        header1: "Habitat",
        image1: "",
        desc1: "Habitat",
        header2: "Eating habits",
        image2: "",
        desc2: "Eating habits",
        header3: "Threat of extinction",
        image3: "",
        desc3: "Threat of extinction",
    },

]